### PR TITLE
add efuse example

### PR DESCRIPTION
**Pull request by thomasstauffer666**

### CODE REVIEW

**Comment by antoine-faravelon** [comment]
I think this example should not be merged as is: we already have the fuser as an example, and this example still uses outdated PULPOS instead of PMSIS API.

**Comment by thomasstauffer666** [comment]
Related to the fuser. Do you talk about the application which writes the fuses via JTAG? When I checked last time it looked like there were just a few predefined boot options (flash/hyperflash). For me it seemed easier to write a tiny application (with an existing header file which uses names instead of e.g. numeric constants) which changes the fuses instead to adapt the tcl scripts. Is there an intention maybe to extend this script and maybe can be parameterized from command line?

With PMSIS do you mean the hal_efuse_* function. I've written the example first with this functions but then had an issue that the functions were not working in for __FREERTOS__ (maybe this is fixed now). But if this is the intended way I could also change the function names.

**Comment by Yaooooo** [comment]
Thank you Thomas for contributing this.
@antoine-faravelon, Thomas is asking for merging into example/native/pulp-os
So I think it's OK here to use pulp-os api. 

For pmsis api based example, @thomasstauffer666 we have one here now:
examples/pmsis/test_features/efuse_burner

Thanks again.

**Comment by thomasstauffer666** [comment]
Ok, thanks for this hint

**Comment by antoine-faravelon** [comment]
For the pre baked app from JTAG, the tcl supports just a few mode, but C app is generic, I just saw it does not seem to be in SDK yet, I will add it.
For the Names, I completely agree, it is much more clear. For the header, I'll see if we can generate it from doc too - with all the meaningful names -, nice catch.
I'll merge your example already. Then, I will push the fuser and we can mix the idea of header + a second version of fuser to have just an init code with creates fuse map from header and fuses that (no tcl, no jtag). Should be able to cover more cases, especially those where jtag is not an option.

**Pull request merged**
